### ISSUE TITLE
It's wonderful. But I am colorblindness.

### ISSUE THREAD

**Issue by zero00072** [gnehs/travel-questions#1]
Yes, I am a colorblindness (deuteranomaly). I can not distinguish your score table between `RED` and `GREEN` so fast so clearly.

You can extend user experience with:

- The guide: [色彩通用設計](https://zh.wikipedia.org/wiki/%E8%89%B2%E5%BD%A9%E9%80%9A%E7%94%A8%E8%A8%AD%E8%A8%88)

My recommend: Change `GREEN` to `BLUE`. It's also not meaning "NOT" but better to distinguish from `RED`.

**Comment by gnehs** [comment]
![image](https://github.com/gnehs/travel-questions/assets/16719720/52da3099-bd28-46b1-b72b-9eac9a9c24d0)
You can enable the color correction feature of the system.

Android: https://support.google.com/accessibility/android/answer/11183305?hl=en#zippy=%2Cuse-color-correction
iOS: https://support.apple.com/en-us/HT207025
