### ISSUE TITLE
多人對照

### ISSUE THREAD

**Issue by Elinaouo** [gnehs/travel-questions#2]
哈囉！我是從朋友出遊表網頁版過來的，想請問這個表有機會出多人對照版嗎？很喜歡這個介面，非常簡約直觀好用，所以想用在年底或明年跟朋友們一起的自由行。

所以想提問有沒有可能第一頁輸入暱稱，後面開始問，最後有幾個人輸入，題目後面就有幾個O或X，每個人的底色不同（直接隨機就好不用給選）這樣多人出遊就可以互相參考了。

非常謝謝您的網站喔，真的超好用！

p.s. 第一次使用這個，如造成困擾還請見諒><

**Comment by turtle0617** [comment]
你好，我這邊有嘗試做了跟你描述差不多的功能。
不知道這樣有解決你的需求嗎？
https://github.com/gnehs/travel-questions/pull/3

**Comment by Elinaouo** [comment]
我點連結看到的還是舊版，沒有看到可以輸入暱稱的地方，請問新版的是更新在哪呢？

**Comment by gnehs** [comment]
> 我點連結看到的還是舊版，沒有看到可以輸入暱稱的地方，請問新版的是更新在哪呢？

新版目前已經上線了！

**Comment by Elinaouo** [comment]
有成功了 謝謝！
